### ISSUE TITLE
ERROR: Task :react-native-update-in-app:generateCodegenSchemaFromJavaScript FAILED

### ISSUE THREAD

**Issue by SetRedEyes** [NepeinAV/react-native-update-in-app#6]
> Task :react-native-update-in-app:generateCodegenSchemaFromJavaScript FAILED
node:internal/fs/utils:353
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/Users/setredeyes/IT/DarlySolutions/cortex/node_modules/react-native-update-in-app/src/codegen'
    at Object.lstatSync (node:fs:1660:3)
    at /Users/setredeyes/IT/DarlySolutions/cortex/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema.js:108:15
    at Array.flatMap (<anonymous>)
    at expandDirectoriesIntoFiles (/Users/setredeyes/IT/DarlySolutions/cortex/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema.js:107:6)
    at combineSchemasInFileList (/Users/setredeyes/IT/DarlySolutions/cortex/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema.js:123:28)
    at combineSchemasInFileListAndWriteToFile (/Users/setredeyes/IT/DarlySolutions/cortex/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema.js:142:20)
    at Object.<anonymous> (/Users/setredeyes/IT/DarlySolutions/cortex/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:76:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/setredeyes/IT/DarlySolutions/cortex/node_modules/react-native-update-in-app/src/codegen'
}

**Comment by SetRedEyes** [comment]
App is not building, but when and i havent got src folder in node_modules/react-native-update-in-app
But when i copied src folder with codegen folder from your repository to my node_modules/react-native-update-in-app
app is started working/.
Please help

**Comment by NepeinAV** [comment]
Try version 1.1.2 please

**Comment by SetRedEyes** [comment]
@NepeinAV Hi! Thank you, app is building

On emulator everything is good and app downloading and i can console.log(event) with event and progress
But on device Android 14  nothing happens and there is no event when tapping on Update App in Modal.
so _**`AppUpdate.downloadApp()`**_ is not calling

So i changed download process to  RNFS in    `${RNFS.TemporaryDirectoryPath}/app-name.apk`;

**Comment by SetRedEyes** [comment]
Also can you please say in which folder app is downloading?
